version: "3.9"
services:

  db:
    expose:
      - 5432

  web:
    build:
      target: production
    environment:
      - "DJANGO_ALLOWED_HOSTS=${MY_DOMAIN}"
      - "DJANGO_CSRF_TRUSTED_ORIGINS=https://${MY_DOMAIN}"
      - "DJANGO_SESSION_COOKIE_SECURE=true"
      - "DJANGO_CSRF_COOKIE_SECURE=true"
      - "DJANGO_SECURE_SSL_REDIRECT=true"
      - "DJANGO_ENV=production"
    restart: unless-stopped
    
    expose:
      - 8000
    command: ["/code/docker-cmd.sh"]


  caddy:
    image: caddy:2.7-alpine
    env_file: .env
    environment:
      - "MY_DOMAIN=${MY_DOMAIN}"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy-data:/data"
      - "caddy-config:/config"
      - type: volume
        source: media-data
        target: /usr/share/caddy/media
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: staticfiles-data
        target: /usr/share/caddy/static
        read_only: true
        volume:
          nocopy: true

volumes:
  caddy-data:
  caddy-config:
  media-data:
  postgres-data:
  staticfiles-data:
