version: "3.9"
services:
  db:
    image: postgres:16.2
    env_file: .env
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -q -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 2s
      retries: 5


  web:
    build: .
    image: nfc_card_game
    env_file: .env
    restart: unless-stopped
    volumes:
      - "staticfiles-data:/var/www/static"
      - "media-data:/var/www/media"
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres-data:
  staticfiles-data:
  media-data:
