version: "3.9"
services:

  db:
    ports:
      - "5432:5432"

  web:
    build:
      target: develop
    image: django-docker
    env_file: .env
    environment:
      - "DJANGO_ENV=develop"
    restart: unless-stopped
    command: ["/code/docker-cmd.sh", "--debug"]
    volumes:
      - "media-data:/var/www/media"
      - ".:/code"  # mount the source code for watching changes
    ports:
      - "8000:8000"


volumes:
  postgres-data:
  media-data:
