# Generated by Django 5.0.3 on 2024-03-31 22:25

import django.db.models.deletion
import nfc_card_game.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_uuid",
                    models.CharField(
                        default=nfc_card_game.main.models.short_uuid, max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("OBV", "Ochtend Bevers"),
                            ("MBV", "Middag Bevers"),
                            ("MAL", "Malicetehorde"),
                            ("SJH", "Sint Jorishorde"),
                            ("COM", "Commoosiehorde"),
                            ("STH", "Sterrenhorde"),
                            ("DOB", "Donkerblauwe troep"),
                            ("SJV", "Sint Jorisvendel"),
                            ("LIB", "Lichtblauwe troep"),
                            ("STV", "Sterrenvendel"),
                            ("EXP", "Explorers"),
                            ("STAF", "Leiding"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.team",
                    ),
                ),
            ],
        ),
    ]
