# Generated by Django 5.0.4 on 2024-05-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='object_id',
        ),
        migrations.AddField(
            model_name='post',
            name='sells',
            field=models.CharField(choices=[('BIJL', 'Bijl'), ('BOOR', 'Boor'), ('RUPSBAND', 'Rupsband'), ('BLAUW', 'Blauw'), ('GROEN', 'Groen'), ('ROOD', 'Rood'), ('MIJNWERKER', 'Mijnwerker'), ('DRILBOOR', 'Drilboor'), ('TUNNELBOOR', 'Tunnelboor')], default=0),
            preserve_default=False,
        ),
    ]
