# Generated by Django 5.0.3 on 2024-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="inventory",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="teammine",
            name="inventory",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
