# Generated by Django 5.0.4 on 2024-05-09 01:01

import nfc_card_game.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_content_type_remove_post_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='card_uuid',
            field=models.CharField(default=nfc_card_game.main.models.short_uuid, max_length=10),
        ),
    ]
