# Generated by Django 5.0.3 on 2024-04-01 20:01

import nfc_card_game.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_player_inventory_alter_teammine_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammine",
            name="card_uuid",
            field=models.CharField(
                default=nfc_card_game.main.models.short_uuid, max_length=10
            ),
        ),
    ]
