# Generated by Django 5.0.4 on 2024-05-09 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_mine_card_uuid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mine",
            unique_together={("team", "currency")},
        ),
    ]
