# Generated by Django 5.0.3 on 2024-04-24 20:59

import nfc_card_game.main.models.player
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_teammine_card_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="card_uuid",
            field=models.CharField(
                default=nfc_card_game.main.models.player.short_uuid,
                max_length=10,
                unique=True,
            ),
        ),
    ]
