# Generated by Django 5.0.3 on 2024-04-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_buys_alter_teammine_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sell_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sells',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AlterField(
            model_name='postrecipe',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
