# Generated by Django 5.0.4 on 2024-05-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_playeritem_amount_alter_teammine_money_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesettings",
            name="mode",
            field=models.CharField(
                choices=[
                    ("trading", "Trading"),
                    ("activities", "Activities"),
                    ("vossenjacht", "Vossenjacht"),
                    ("color", "Color"),
                ],
                default="trading",
                max_length=50,
            ),
        ),
    ]
