# Generated by Django 5.0.3 on 2024-04-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_post_sell_amount_alter_post_sells_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mine",
        ),
        migrations.RemoveField(
            model_name="item",
            name="amount",
        ),
        migrations.AddField(
            model_name="item",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.team",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("MINE", "Mine"),
                    ("RESOURCE", "Resource"),
                    ("MINER", "Miner"),
                ],
                default="RESOURCE",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
