# Generated by Django 5.0.4 on 2024-05-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_gamesettings_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesettings",
            name="mode",
            field=models.CharField(
                choices=[
                    ("trading", "Trading"),
                    ("activiteiten", "Activities"),
                    ("vossen", "Vossenjacht"),
                    ("color", "Color"),
                ],
                default="trading",
                max_length=50,
            ),
        ),
    ]
