# Generated by Django 5.0.4 on 2024-09-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_gamesettings_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorMatchSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_state",
                    models.CharField(
                        choices=[("RUNNING", "Running"), ("FINISHED", "Finished")],
                        default="RUNNING",
                    ),
                ),
                ("auto_rotate_colors", models.BooleanField(default=False)),
            ],
        ),
    ]
