# Generated by Django 5.0.3 on 2024-04-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mine'),
        ('main', '0008_remove_teammine_card_uuid_alter_item_unique_together'),
    ]

    operations = [
    ]
