# Generated by Django 5.0.4 on 2024-05-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_recipes_alter_post_sells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recipes',
        ),
        migrations.AddField(
            model_name='postrecipe',
            name='required',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='sells',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
