# Generated by Django 5.0.4 on 2024-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_post_recipes_postrecipe_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('RESOURCE', 'Resource'), ('FACTORY', 'Factory'), ('COIN', 'Coin')], default=0),
            preserve_default=False,
        ),
    ]
