# Generated by Django 5.0.4 on 2024-04-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_merge_20240425_2220"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["type", "name"]},
        ),
        migrations.AlterModelOptions(
            name="teammine",
            options={"ordering": ["team", "mine"]},
        ),
        migrations.AddField(
            model_name="player",
            name="activities",
            field=models.ManyToManyField(to="main.activity"),
        ),
    ]
