# Generated by Django 5.0.4 on 2024-04-29 20:11

import nfc_card_game.main.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_activity_alter_item_options_alter_teammine_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("trading", "Trading"),
                            ("activities", "Activities"),
                            ("color", "Color"),
                        ],
                        default="trading",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="card_uuid",
            field=models.CharField(
                default=nfc_card_game.main.models.utils.short_uuid, max_length=10
            ),
        ),
    ]
