# Generated by Django 5.0.4 on 2024-05-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_amount_teammine_money_teammineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('COIN', 'Coin'), ('RESOURCE', 'Resource'), ('MINER', 'Miner')]),
        ),
    ]
