# Generated by Django 5.0.3 on 2024-05-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_player_color_player_color_points_alter_player_team"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("type", "currency", "team")},
        ),
    ]
